#!/usr/bin/env php
<?php
/**
 * @copyright   Copyright (c) http://careyshop.cn All rights reserved.
 *
 * CareyShop    命令行入口文件
 *
 * @author      zxm <252404501@qq.com>
 * @date        2017/5/4
 */

// 定义项目路径
define('APP_PATH', __DIR__ . '/application/');

// 加载框架引导文件
require __DIR__ . '/thinkphp/console.php';